version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - postgres.env
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      net:
        ipv4_address: 172.19.0.2

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080"
    networks:
      net:
        ipv4_address: 172.19.0.3

  front:
    image: nomak92/pyrnr
    restart: always
    environment:
      - "POSTGRES_HOST=db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      net:
        ipv4_address: 172.19.0.4

volumes:
  database-data:

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"