apiVersion: v1
kind: Service
metadata:
  name: pyrnr-frontend
  labels:
    app: pyrnr
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  clusterIP: None
  selector:
    app: pyrnr