# Generated by Django 3.2 on 2021-04-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_script_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='user_id',
            new_name='user',
        ),
    ]
